<?php switch($content){
	case "home";
		include("home.php");
		break;
	case "tampil_ebook";
		include("ebook_tampil.php");
		break;
	case "tambah_ebook";
		include("ebook_tambah.php");
		break;
	case "edit_ebook";
		include("ebook_edit.php");
		break;
	case "tampil_ebooks";
		include("ebooks_tampil.php");
		break;
	case "tambah_ebooks";
		include("ebooks_tambah.php");
		break;
	case "edit_ebooks";
		include("ebooks_edit.php");
		break;
	case "status_ebooks";
		include("ebooks_status.php");
		break;
	case "tampil_soal";
		include("soal_tampil.php");
		break;
	case "tambah_soal";
		include("soal_tambah.php");
		break;
	case "edit_soal";
		include("soal_edit.php");
		break;
	case "mk_arsip";
		include("arsip_view_mk.php");
		break;
	case "cat_arsip";
		include("arsip_view_cat.php");
		break;
	case "view_arsip";
		include("arsip_view.php");
		break;
	case "all_arsip";
		include("arsip_view_all.php");
		break;
	case "tambah_arsip";
		include("arsip_form.php");
		break;
	case "tambah_arsip_front";
		include("arsip_add_front.php");
		break;
	case "tambah_arsip_back";
		include("arsip_add_back.php");
		break;
	case "edit_arsip";
		include("arsip_edit.php");
		break;
	case "edit_arsip_front";
		include("arsip_edit_front.php");
		break;
	case "edit_arsip_back";
		include("arsip_edit_back.php");
		break;
	case "trash_arsip";
		include("arsip_view_trash.php");
		break;
	case "project_view";
		include("project_view.php");
		break;
	case "project_upload";
		include("project_upload.php");
		break;
	case "manajemen_artikel";
		include("manajemen_artikel.php");
		break;
	case "artikel_status";
		include("manajemen_artikel_status.php");
		break;
	case "edit_manajemen_artikel";
		include("edit_manajemen_artikel.php");
		break;
	case "tambah_artikel";
		include("tambah_artikel.php");
		break;
	case "manajemen_link";
		include("manajemen_link.php");
		break;
	case "edit_link";
		include("link/edit_link.php");
		break;
	case "tambah_link";
		include("link/tambah_link.php");
		break;
	}
	?>